import { 
  Store, 
  Category, 
  IPhoneSeries,
  User, 
  InventoryItem, 
  StockTransaction, 
  ReturnItem, 
  AttendanceRecord, 
  ActivityLog, 
  AppNotification 
} from './types';
import { hashPasswordSync } from './utils/security';

export const INITIAL_IPHONE_SERIES: IPhoneSeries[] = [
  { id: 'series-x', nama_seri: 'iPhone X', deskripsi: 'Layar Super Retina OLED 5.8", Apple A11 Bionic', tahun_rilis: 2017, urutan: 1 },
  { id: 'series-xr', nama_seri: 'iPhone XR', deskripsi: 'Layar Liquid Retina HD 6.1", Apple A12 Bionic', tahun_rilis: 2018, urutan: 2 },
  { id: 'series-xs', nama_seri: 'iPhone XS / XS Max', deskripsi: 'Layar Super Retina OLED 5.8" & 6.5", Apple A12 Bionic', tahun_rilis: 2018, urutan: 3 },
  { id: 'series-11', nama_seri: 'iPhone 11', deskripsi: 'Layar Liquid Retina HD 6.1", Dual Camera, A13 Bionic', tahun_rilis: 2019, urutan: 4 },
  { id: 'series-11p', nama_seri: 'iPhone 11 Pro', deskripsi: 'Layar Super Retina XDR OLED 5.8", Triple Camera', tahun_rilis: 2019, urutan: 5 },
  { id: 'series-11pm', nama_seri: 'iPhone 11 Pro Max', deskripsi: 'Layar Super Retina XDR OLED 6.5", Triple Camera', tahun_rilis: 2019, urutan: 6 },
  { id: 'series-12m', nama_seri: 'iPhone 12 Mini', deskripsi: 'Layar Super Retina XDR OLED 5.4", 5G, A14 Bionic', tahun_rilis: 2020, urutan: 7 },
  { id: 'series-12', nama_seri: 'iPhone 12', deskripsi: 'Layar Super Retina XDR OLED 6.1", Ceramic Shield, 5G', tahun_rilis: 2020, urutan: 8 },
  { id: 'series-12p', nama_seri: 'iPhone 12 Pro', deskripsi: 'Layar OLED 6.1", LiDAR Scanner, Frame Stainless Steel', tahun_rilis: 2020, urutan: 9 },
  { id: 'series-12pm', nama_seri: 'iPhone 12 Pro Max', deskripsi: 'Layar OLED 6.7", Sensor-shift OIS, LiDAR Scanner', tahun_rilis: 2020, urutan: 10 },
  { id: 'series-13m', nama_seri: 'iPhone 13 Mini', deskripsi: 'Layar Super Retina XDR OLED 5.4", Apple A15 Bionic', tahun_rilis: 2021, urutan: 11 },
  { id: 'series-13', nama_seri: 'iPhone 13', deskripsi: 'Layar Super Retina XDR OLED 6.1", Apple A15 Bionic', tahun_rilis: 2021, urutan: 12 },
  { id: 'series-13p', nama_seri: 'iPhone 13 Pro', deskripsi: 'Layar ProMotion 120Hz 6.1", Triple Camera Cinematic', tahun_rilis: 2021, urutan: 13 },
  { id: 'series-13pm', nama_seri: 'iPhone 13 Pro Max', deskripsi: 'Layar ProMotion 120Hz 6.7", Baterai Maksimal', tahun_rilis: 2021, urutan: 14 },
  { id: 'series-14', nama_seri: 'iPhone 14', deskripsi: 'Layar Super Retina XDR 6.1", Crash Detection, Photonic Engine', tahun_rilis: 2022, urutan: 15 },
  { id: 'series-14pls', nama_seri: 'iPhone 14 Plus', deskripsi: 'Layar Super Retina XDR 6.7", All-day battery life', tahun_rilis: 2022, urutan: 16 },
  { id: 'series-14p', nama_seri: 'iPhone 14 Pro', deskripsi: 'Dynamic Island, Always-On Display, 48MP Camera, A16 Bionic', tahun_rilis: 2022, urutan: 17 },
  { id: 'series-14pm', nama_seri: 'iPhone 14 Pro Max', deskripsi: 'Dynamic Island, 48MP Camera, Ceramic Shield 6.7"', tahun_rilis: 2022, urutan: 18 },
  { id: 'series-15', nama_seri: 'iPhone 15', deskripsi: 'Dynamic Island, USB-C Port, 48MP Main Camera, A16 Bionic', tahun_rilis: 2023, urutan: 19 },
  { id: 'series-15pls', nama_seri: 'iPhone 15 Plus', deskripsi: 'Dynamic Island 6.7", USB-C Port, Super Battery', tahun_rilis: 2023, urutan: 20 },
  { id: 'series-15p', nama_seri: 'iPhone 15 Pro', deskripsi: 'Grade 5 Titanium, Action Button, USB-C 3.0, A17 Pro', tahun_rilis: 2023, urutan: 21 },
  { id: 'series-15pm', nama_seri: 'iPhone 15 Pro Max', deskripsi: 'Titanium Body, 5x Telephoto Tetraprism, A17 Pro Chip', tahun_rilis: 2023, urutan: 22 },
  { id: 'series-16', nama_seri: 'iPhone 16', deskripsi: 'Camera Control Button, Apple Intelligence, A18 Chip', tahun_rilis: 2024, urutan: 23 },
  { id: 'series-16pm', nama_seri: 'iPhone 16 Pro Max', deskripsi: 'Titanium 6.9" Display, 4K120fps Dolby Vision, A18 Pro', tahun_rilis: 2024, urutan: 24 },
  { id: 'series-univ', nama_seri: 'Universal / Multi-Model', deskripsi: 'Tools, Lem OCA, Toolkit, Baut, & Part Multi Seri', tahun_rilis: 2025, urutan: 25 },
];

export const IPHONE_MODELS: string[] = INITIAL_IPHONE_SERIES.map((s) => s.nama_seri);

export const formatRupiah = (value: number | undefined | null): string => {
  if (value === undefined || value === null || isNaN(value)) return 'Rp 0';
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
};

export const INITIAL_STORES: Store[] = [
  {
    id: 'store-a',
    nama_toko: 'Toko A',
    cabang: 'Cabang Medan (Pusat)',
    alamat: 'Jl. Gatot Subroto No. 88, Medan Petisah, Medan',
    nomor_telepon: '0812-3456-7890',
    status: 'AKTIF',
    pic_name: 'Budi Santoso',
    jam_operasional: '08:30 - 20:00 WIB',
    jam_masuk_standar: '08:30',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    foto_profil: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="22" fill="%234f46e5"/><path d="M30 70 L50 25 L70 70 Z" fill="white" opacity="0.95"/><circle cx="50" cy="52" r="10" fill="%234f46e5"/></svg>',
    created_at: '2026-01-10',
    updated_at: '2026-08-15',
  },
  {
    id: 'store-b',
    nama_toko: 'Toko B',
    cabang: 'Cabang Jakarta Barat',
    alamat: 'Ruko Roxy Mas Blok D2 No. 14, Gambir, Jakarta Barat',
    nomor_telepon: '0813-9876-5432',
    status: 'AKTIF',
    pic_name: 'Hendra Gunawan',
    jam_operasional: '09:00 - 21:00 WIB',
    jam_masuk_standar: '09:00',
    jam_pulang_standar: '17:30',
    toleransi_keterlambatan_menit: 0,
    foto_profil: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="22" fill="%230ea5e9"/><circle cx="50" cy="50" r="28" fill="white" opacity="0.95"/><rect x="42" y="32" width="16" height="36" rx="4" fill="%230ea5e9"/></svg>',
    created_at: '2026-02-01',
    updated_at: '2026-08-20',
  },
  {
    id: 'store-c',
    nama_toko: 'Toko C',
    cabang: 'Cabang Surabaya',
    alamat: 'Plaza Marina Lt. 2 No. 105, Wonocolo, Surabaya',
    nomor_telepon: '0811-2233-4455',
    status: 'AKTIF',
    pic_name: 'Rudi Hermawan',
    jam_operasional: '10:00 - 21:00 WIB',
    jam_masuk_standar: '10:00',
    jam_pulang_standar: '18:00',
    toleransi_keterlambatan_menit: 0,
    foto_profil: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="22" fill="%2310b981"/><path d="M26 50 L50 26 L74 50 L50 74 Z" fill="white" opacity="0.95"/></svg>',
    created_at: '2026-03-12',
    updated_at: '2026-08-18',
  },
  {
    id: 'store-d',
    nama_toko: 'Toko D',
    cabang: 'Cabang Bandung',
    alamat: 'BEC Mall Lt. 3 Blok E-08, Jl. Purnawarman, Bandung',
    nomor_telepon: '0856-7788-9900',
    status: 'AKTIF',
    pic_name: 'Asep Kusnadi',
    jam_operasional: '09:30 - 20:30 WIB',
    jam_masuk_standar: '09:30',
    jam_pulang_standar: '17:30',
    toleransi_keterlambatan_menit: 0,
    foto_profil: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="22" fill="%238b5cf6"/><circle cx="38" cy="42" r="16" fill="white"/><circle cx="62" cy="58" r="16" fill="white" opacity="0.8"/></svg>',
    created_at: '2026-04-05',
    updated_at: '2026-08-22',
  },
  {
    id: 'store-e',
    nama_toko: 'Toko E',
    cabang: 'Cabang Makassar',
    alamat: 'MTC Karebosi Lt. 1 Blok B No. 22, Wajo, Makassar',
    nomor_telepon: '0878-1122-3344',
    status: 'AKTIF',
    pic_name: 'Faisal Ramli',
    jam_operasional: '09:00 - 20:00 WITA',
    jam_masuk_standar: '09:00',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    foto_profil: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="22" fill="%23f59e0b"/><polygon points="50,22 61,43 84,46 67,62 72,85 50,73 28,85 33,62 16,46 39,43" fill="white"/></svg>',
    created_at: '2026-05-18',
    updated_at: '2026-08-25',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat-1', nama_kategori: 'LCD & Touchscreen', deskripsi: 'Layar OLED, In-cell, Incell iPhone', created_at: '2026-01-01' },
  { id: 'cat-2', nama_kategori: 'Baterai (Battery Pack)', deskripsi: 'Battery pack original & high capacity BMS transfer', created_at: '2026-01-01' },
  { id: 'cat-3', nama_kategori: 'Kamera & Sensor', deskripsi: 'Kamera depan/belakang, TrueDepth Face ID, sensor proximity', created_at: '2026-01-02' },
  { id: 'cat-4', nama_kategori: 'Speaker & Earpiece', deskripsi: 'Buzzer speaker bawah, earpiece atas, mic filter', created_at: '2026-01-02' },
  { id: 'cat-5', nama_kategori: 'Flexible & Port Charger', deskripsi: 'Flex on/off, volume, port lightning, USB Type-C', created_at: '2026-01-03' },
  { id: 'cat-6', nama_kategori: 'IC & Chipset Motherboard', deskripsi: 'IC Power (PMIC), Audio Codec, Baseband, NAND', created_at: '2026-01-03' },
  { id: 'cat-7', nama_kategori: 'Casing & Backglass', deskripsi: 'Frame housing, back glass backdoor replacement', created_at: '2026-01-04' },
  { id: 'cat-8', nama_kategori: 'Tool Service & Lem Adhesive', deskripsi: 'Lem LCD T7000/B7000, baterai tape, solder wire', created_at: '2026-01-04' },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-super',
    name: 'Alfin Maulana (Super Admin)',
    nama: 'Alfin Maulana (Super Admin)',
    username: 'superadmin@gmail.com',
    nomor_telepon: '081299887700',
    no_hp: '081299887700',
    email: 'superadmin@gmail.com',
    email_tertaut: 'superadmin@gmail.com',
    is_email_verified: true,
    email_verified_at: '2026-01-01',
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'SUPER_ADMIN',
    store_id: null,
    status: 'AKTIF',
    position: 'Chief Technical & Inventory Officer',
    avatar: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="50" fill="%231e1b4b"/><circle cx="50" cy="38" r="18" fill="%23818cf8"/><path d="M22 84 C22 66 34 60 50 60 C66 60 78 66 78 84 Z" fill="%23c7d2fe"/></svg>',
    jam_masuk_standar: '08:30',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-01-01',
  },
  {
    id: 'user-admin-a',
    name: 'Budi Santoso (Admin Medan)',
    nama: 'Budi Santoso (Admin Medan)',
    username: 'budi.santoso.medan@gmail.com',
    nomor_telepon: '081266778891',
    no_hp: '081266778891',
    email: 'budi.santoso.medan@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'ADMIN_TOKO',
    store_id: 'store-a',
    status: 'AKTIF',
    position: 'Kepala Toko Medan',
    avatar: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><rect width="100" height="100" rx="50" fill="%23064e3b"/><circle cx="50" cy="38" r="18" fill="%2334d399"/><path d="M22 84 C22 66 34 60 50 60 C66 60 78 66 78 84 Z" fill="%23a7f3d0"/></svg>',
    jam_masuk_standar: '08:30',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-01-10',
  },
  {
    id: 'user-admin-b',
    name: 'Hendra Gunawan (Admin Jakarta)',
    nama: 'Hendra Gunawan (Admin Jakarta)',
    username: 'hendra.gunawan.jkt@gmail.com',
    nomor_telepon: '081311223345',
    no_hp: '081311223345',
    email: 'hendra.gunawan.jkt@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'ADMIN_TOKO',
    store_id: 'store-b',
    status: 'AKTIF',
    position: 'Kepala Toko Jakarta',
    jam_masuk_standar: '09:00',
    jam_pulang_standar: '18:00',
    toleransi_keterlambatan_menit: 5,
    created_at: '2026-02-01',
  },
  {
    id: 'user-admin-c',
    name: 'Rudi Hermawan (Admin Surabaya)',
    nama: 'Rudi Hermawan (Admin Surabaya)',
    username: 'rudi.hermawan.sby@gmail.com',
    nomor_telepon: '081244556678',
    no_hp: '081244556678',
    email: 'rudi.hermawan.sby@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'ADMIN_TOKO',
    store_id: 'store-c',
    status: 'AKTIF',
    position: 'Kepala Toko Surabaya',
    jam_masuk_standar: '10:00',
    jam_pulang_standar: '18:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-03-12',
  },
  {
    id: 'user-admin-d',
    name: 'Asep Kusnadi (Admin Bandung)',
    nama: 'Asep Kusnadi (Admin Bandung)',
    username: 'asep.kusnadi.bdg@gmail.com',
    nomor_telepon: '081199887767',
    no_hp: '081199887767',
    email: 'asep.kusnadi.bdg@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'ADMIN_TOKO',
    store_id: 'store-d',
    status: 'AKTIF',
    position: 'Kepala Toko Bandung',
    jam_masuk_standar: '09:30',
    jam_pulang_standar: '17:30',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-04-05',
  },
  {
    id: 'user-admin-e',
    name: 'Faisal Ramli (Admin Makassar)',
    nama: 'Faisal Ramli (Admin Makassar)',
    username: 'faisal.ramli.mks@gmail.com',
    nomor_telepon: '081933445567',
    no_hp: '081933445567',
    email: 'faisal.ramli.mks@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'ADMIN_TOKO',
    store_id: 'store-e',
    status: 'AKTIF',
    position: 'Kepala Toko Makassar',
    jam_masuk_standar: '09:00',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-05-18',
  },
  {
    id: 'user-staff-a1',
    name: 'Dimas Prasetyo',
    nama: 'Dimas Prasetyo',
    username: 'dimas.prasetyo.medan@gmail.com',
    nomor_telepon: '081277889901',
    no_hp: '081277889901',
    email: 'dimas.prasetyo.medan@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'KARYAWAN',
    store_id: 'store-a',
    status: 'AKTIF',
    position: 'Teknisi iPhone Senior',
    jam_masuk_standar: '08:30',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-01-15',
  },
  {
    id: 'user-staff-a2',
    name: 'Rian Pratama',
    nama: 'Rian Pratama',
    username: 'rian.pratama.medan@gmail.com',
    nomor_telepon: '081277889902',
    no_hp: '081277889902',
    email: 'rian.pratama.medan@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'KARYAWAN',
    store_id: 'store-a',
    status: 'AKTIF',
    position: 'Staff Frontdesk & Service',
    jam_masuk_standar: '08:30',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-02-01',
  },
  {
    id: 'user-staff-b1',
    name: 'Kevin Wijaya',
    nama: 'Kevin Wijaya',
    username: 'kevin.wijaya.jkt@gmail.com',
    nomor_telepon: '081322334455',
    no_hp: '081322334455',
    email: 'kevin.wijaya.jkt@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'KARYAWAN',
    store_id: 'store-b',
    status: 'AKTIF',
    position: 'Teknisi Hardware',
    jam_masuk_standar: '09:00',
    jam_pulang_standar: '18:00',
    toleransi_keterlambatan_menit: 5,
    created_at: '2026-02-10',
  },
  {
    id: 'user-staff-c1',
    name: 'Agus Santoso',
    nama: 'Agus Santoso',
    username: 'agus.santoso.sby@gmail.com',
    nomor_telepon: '081233445566',
    no_hp: '081233445566',
    email: 'agus.santoso.sby@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'KARYAWAN',
    store_id: 'store-c',
    status: 'AKTIF',
    position: 'Teknisi Motherboard',
    jam_masuk_standar: '10:00',
    jam_pulang_standar: '18:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-03-20',
  },
  {
    id: 'user-staff-d1',
    name: 'Dadan Suhendar',
    nama: 'Dadan Suhendar',
    username: 'dadan.suhendar.bdg@gmail.com',
    nomor_telepon: '085611223344',
    no_hp: '085611223344',
    email: 'dadan.suhendar.bdg@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'KARYAWAN',
    store_id: 'store-d',
    status: 'AKTIF',
    position: 'Teknisi Layar & Baterai',
    jam_masuk_standar: '09:30',
    jam_pulang_standar: '17:30',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-04-10',
  },
  {
    id: 'user-staff-e1',
    name: 'Ilham Syam',
    nama: 'Ilham Syam',
    username: 'ilham.syam.mks@gmail.com',
    nomor_telepon: '087855667788',
    no_hp: '087855667788',
    email: 'ilham.syam.mks@gmail.com',
    email_tertaut: undefined,
    is_email_verified: false,
    password: hashPasswordSync('password123'),
    password_hash: hashPasswordSync('password123'),
    must_change_password: false,
    role: 'KARYAWAN',
    store_id: 'store-e',
    status: 'AKTIF',
    position: 'Teknisi & Customer Service',
    jam_masuk_standar: '09:00',
    jam_pulang_standar: '17:00',
    toleransi_keterlambatan_menit: 0,
    created_at: '2026-05-20',
  },
];

// Helper to determine status based on stock & min stock
export const calculateStockStatus = (stock: number, minStock: number) => {
  if (stock <= 0) return 'HABIS';
  if (stock <= minStock) return 'MENIPIS';
  return 'AMAN';
};

export const INITIAL_INVENTORY: InventoryItem[] = [
  // STORE A (Medan) items
  {
    id: 'inv-a-1',
    store_id: 'store-a',
    category_id: 'cat-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    stok: 24,
    stok_minimum: 5,
    satuan: 'pcs',
    keterangan: 'Warna Hitam, TrueTone support, include bracket kamera',
    status: 'AMAN',
    created_at: '2026-01-10',
    updated_at: '2026-09-01',
  },
  {
    id: 'inv-a-2',
    store_id: 'store-a',
    category_id: 'cat-1',
    kode_barang: 'LCD-IP14PM-ORI',
    nama_barang: 'LCD iPhone 14 Pro Max OLED 120Hz ProMotion',
    model_iphone: 'iPhone 14 Pro Max',
    harga_beli: 1850000,
    harga_jual: 2400000,
    stok: 4,
    stok_minimum: 5,
    satuan: 'pcs',
    keterangan: 'Original Cabutan Grade A+, 100% Tested',
    status: 'MENIPIS',
    created_at: '2026-01-12',
    updated_at: '2026-09-01',
  },
  {
    id: 'inv-a-3',
    store_id: 'store-a',
    category_id: 'cat-2',
    kode_barang: 'BAT-IP11-HC',
    nama_barang: 'Baterai iPhone 11 High Capacity 3500mAh (Kitsune)',
    model_iphone: 'iPhone 11',
    harga_beli: 150000,
    harga_jual: 250000,
    stok: 18,
    stok_minimum: 6,
    satuan: 'pcs',
    keterangan: 'Free adhesive tape baterai & segel garansi 6 bulan',
    status: 'AMAN',
    created_at: '2026-01-15',
    updated_at: '2026-08-28',
  },
  {
    id: 'inv-a-4',
    store_id: 'store-a',
    category_id: 'cat-2',
    kode_barang: 'BAT-IP12-ORI',
    nama_barang: 'Baterai iPhone 12 / 12 Pro Original IC On',
    model_iphone: 'iPhone 12',
    harga_beli: 220000,
    harga_jual: 330000,
    stok: 0,
    stok_minimum: 4,
    satuan: 'pcs',
    keterangan: 'Kondisi 0 Cycle Count, Support BMS transfer',
    status: 'HABIS',
    created_at: '2026-01-16',
    updated_at: '2026-08-30',
  },
  {
    id: 'inv-a-5',
    store_id: 'store-a',
    category_id: 'cat-3',
    kode_barang: 'CAM-IP13-REAR',
    nama_barang: 'Kamera Belakang Dual iPhone 13 Original',
    model_iphone: 'iPhone 13',
    harga_beli: 550000,
    harga_jual: 750000,
    stok: 8,
    stok_minimum: 3,
    satuan: 'pcs',
    keterangan: 'Sensor shift OIS jernih, no getar',
    status: 'AMAN',
    created_at: '2026-01-20',
    updated_at: '2026-08-25',
  },
  {
    id: 'inv-a-6',
    store_id: 'store-a',
    category_id: 'cat-5',
    kode_barang: 'FLX-IP14-CHG',
    nama_barang: 'Flexible Port Charger Lightning iPhone 14 Midnight',
    model_iphone: 'iPhone 14',
    harga_beli: 95000,
    harga_jual: 160000,
    stok: 12,
    stok_minimum: 4,
    satuan: 'pcs',
    keterangan: 'Include microphone & antena sinyal',
    status: 'AMAN',
    created_at: '2026-02-01',
    updated_at: '2026-08-29',
  },
  {
    id: 'inv-a-7',
    store_id: 'store-a',
    category_id: 'cat-6',
    kode_barang: 'IC-AUDIO-IP7P',
    nama_barang: 'IC Audio iPhone 7 / 7 Plus (338S00105)',
    model_iphone: 'iPhone 7 / 7 Plus',
    harga_beli: 45000,
    harga_jual: 90000,
    stok: 35,
    stok_minimum: 10,
    satuan: 'pcs',
    keterangan: 'Fix loop audio / mic call',
    status: 'AMAN',
    created_at: '2026-02-05',
    updated_at: '2026-08-20',
  },
  {
    id: 'inv-a-8',
    store_id: 'store-a',
    category_id: 'cat-7',
    kode_barang: 'BG-IP13-BLUE',
    nama_barang: 'Backglass Kaca Belakang iPhone 13 Big Hole Blue',
    model_iphone: 'iPhone 13',
    harga_beli: 60000,
    harga_jual: 120000,
    stok: 15,
    stok_minimum: 5,
    satuan: 'pcs',
    keterangan: 'Big hole mempermudah pasang tanpa copot ring kamera',
    status: 'AMAN',
    created_at: '2026-02-10',
    updated_at: '2026-08-21',
  },
  {
    id: 'inv-a-9',
    store_id: 'store-a',
    category_id: 'cat-8',
    kode_barang: 'TOOL-LEM-T7000',
    nama_barang: 'Lem LCD T-7000 Black 110ml Original Zhanlida',
    model_iphone: 'Universal / Multi-Model',
    harga_beli: 25000,
    harga_jual: 45000,
    stok: 9,
    stok_minimum: 3,
    satuan: 'botol',
    keterangan: 'Lem perekat khusus LCD & frame HP',
    status: 'AMAN',
    created_at: '2026-02-15',
    updated_at: '2026-08-26',
  },
  {
    id: 'inv-a-10',
    store_id: 'store-a',
    category_id: 'cat-3',
    kode_barang: 'SENSOR-IP12',
    nama_barang: 'Sensor Face ID & Earpiece Flex iPhone 12',
    model_iphone: 'iPhone 12',
    harga_beli: 250000,
    harga_jual: 350000,
    stok: 14,
    stok_minimum: 4,
    satuan: 'pcs',
    keterangan: 'Komponen sensor proximity & flood illuminator',
    status: 'AMAN',
    created_at: '2026-02-18',
    updated_at: '2026-09-01',
  },
  {
    id: 'inv-a-11',
    store_id: 'store-a',
    category_id: 'cat-3',
    kode_barang: 'SENSOR-IP15',
    nama_barang: 'Sensor Dynamic Island Proximity Flex iPhone 15',
    model_iphone: 'iPhone 15',
    harga_beli: 380000,
    harga_jual: 520000,
    stok: 8,
    stok_minimum: 3,
    satuan: 'pcs',
    keterangan: 'Khusus iPhone 15 standar, tidak kompatibel dengan iPhone 12/13/14',
    status: 'AMAN',
    created_at: '2026-02-20',
    updated_at: '2026-09-01',
  },

  // STORE B (Jakarta Barat) items
  {
    id: 'inv-b-1',
    store_id: 'store-b',
    category_id: 'cat-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    stok: 15,
    stok_minimum: 5,
    satuan: 'pcs',
    keterangan: 'Stock Jakarta Barat',
    status: 'AMAN',
    created_at: '2026-02-01',
    updated_at: '2026-08-30',
  },
  {
    id: 'inv-b-2',
    store_id: 'store-b',
    category_id: 'cat-2',
    kode_barang: 'BAT-IP13PM-HC',
    nama_barang: 'Baterai iPhone 13 Pro Max 4352mAh High Capacity',
    model_iphone: 'iPhone 13 Pro Max',
    harga_beli: 190000,
    harga_jual: 295000,
    stok: 2,
    stok_minimum: 4,
    satuan: 'pcs',
    keterangan: 'Stok menipis, segera restock',
    status: 'MENIPIS',
    created_at: '2026-02-01',
    updated_at: '2026-08-28',
  },
  {
    id: 'inv-b-3',
    store_id: 'store-b',
    category_id: 'cat-5',
    kode_barang: 'FLX-IP15-TYPEC',
    nama_barang: 'Flexible Charging Port USB Type-C iPhone 15 Pro',
    model_iphone: 'iPhone 15 Pro',
    harga_beli: 120000,
    harga_jual: 210000,
    stok: 7,
    stok_minimum: 3,
    satuan: 'pcs',
    keterangan: 'Fast charging support 27W & USB-3 speed',
    status: 'AMAN',
    created_at: '2026-02-10',
    updated_at: '2026-08-30',
  },

  // STORE C (Surabaya) items
  {
    id: 'inv-c-1',
    store_id: 'store-c',
    category_id: 'cat-1',
    kode_barang: 'LCD-IP15-OLED',
    nama_barang: 'LCD iPhone 15 Dynamic Island Super Retina XDR',
    model_iphone: 'iPhone 15',
    harga_beli: 1200000,
    harga_jual: 1650000,
    stok: 6,
    stok_minimum: 2,
    satuan: 'pcs',
    keterangan: 'Original Equipment Manufacturer (OEM)',
    status: 'AMAN',
    created_at: '2026-03-12',
    updated_at: '2026-08-31',
  },
  {
    id: 'inv-c-2',
    store_id: 'store-c',
    category_id: 'cat-2',
    kode_barang: 'BAT-IP11-HC',
    nama_barang: 'Baterai iPhone 11 High Capacity 3500mAh',
    model_iphone: 'iPhone 11',
    harga_beli: 150000,
    harga_jual: 250000,
    stok: 10,
    stok_minimum: 4,
    satuan: 'pcs',
    keterangan: 'Cabang Surabaya',
    status: 'AMAN',
    created_at: '2026-03-12',
    updated_at: '2026-08-29',
  },

  // STORE D (Bandung) items
  {
    id: 'inv-d-1',
    store_id: 'store-d',
    category_id: 'cat-1',
    kode_barang: 'LCD-IP12P-OLED',
    nama_barang: 'LCD iPhone 12 Pro OLED RJ Premium',
    model_iphone: 'iPhone 12 Pro',
    harga_beli: 520000,
    harga_jual: 720000,
    stok: 8,
    stok_minimum: 3,
    satuan: 'pcs',
    keterangan: 'Cabang Bandung BEC Mall',
    status: 'AMAN',
    created_at: '2026-04-05',
    updated_at: '2026-08-28',
  },

  // STORE E (Makassar) items
  {
    id: 'inv-e-1',
    store_id: 'store-e',
    category_id: 'cat-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    stok: 11,
    stok_minimum: 4,
    satuan: 'pcs',
    keterangan: 'Cabang Makassar MTC Karebosi',
    status: 'AMAN',
    created_at: '2026-05-18',
    updated_at: '2026-08-30',
  },
];

export const INITIAL_TRANSACTIONS: StockTransaction[] = [
  {
    id: 'trx-001',
    store_id: 'store-a',
    inventory_id: 'inv-a-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 20,
    stok_sebelum: 4,
    stok_sesudah: 24,
    alasan: 'Restock pengiriman dari Gudang Distributor Jakarta',
    keterangan: 'PO #2026-08-8821 via JNE Cargo',
    tanggal: '2026-08-28',
    waktu: '10:15:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-08-28 10:15:00',
  },
  {
    id: 'trx-002',
    store_id: 'store-a',
    inventory_id: 'inv-a-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 2,
    stok_sebelum: 26,
    stok_sesudah: 24,
    alasan: 'Terjual / Service Ganti LCD Customer',
    keterangan: 'Nota Servis #MED-9941 dan #MED-9945',
    tanggal: '2026-08-29',
    waktu: '14:30:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-08-29 14:30:00',
  },
  {
    id: 'trx-003',
    store_id: 'store-a',
    inventory_id: 'inv-a-2',
    kode_barang: 'LCD-IP14PM-ORI',
    nama_barang: 'LCD iPhone 14 Pro Max OLED 120Hz ProMotion',
    model_iphone: 'iPhone 14 Pro Max',
    harga_beli: 1850000,
    harga_jual: 2400000,
    jenis: 'RUSAK',
    direction: '-',
    jumlah: 1,
    stok_sebelum: 5,
    stok_sesudah: 4,
    alasan: 'Garis hijau saat pengetesan teknisi (Dead on Arrival)',
    keterangan: 'Dibuatkan form claim retur ke supplier',
    tanggal: '2026-08-30',
    waktu: '11:20:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-08-30 11:20:00',
  },
  {
    id: 'trx-004',
    store_id: 'store-a',
    inventory_id: 'inv-a-4',
    kode_barang: 'BAT-IP12-ORI',
    nama_barang: 'Baterai iPhone 12 / 12 Pro Original IC On',
    model_iphone: 'iPhone 12',
    harga_beli: 220000,
    harga_jual: 330000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 3,
    stok_sebelum: 3,
    stok_sesudah: 0,
    alasan: 'Terjual & Penggantian baterai kesehatan drop',
    keterangan: 'Stok sekarang habis (0)',
    tanggal: '2026-08-31',
    waktu: '16:45:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-08-31 16:45:00',
  },
  // Store A - September 2026 (Today & This Week)
  {
    id: 'trx-a-sep-01',
    store_id: 'store-a',
    inventory_id: 'inv-a-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 15,
    stok_sebelum: 9,
    stok_sesudah: 24,
    alasan: 'Restock Batch Awal Bulan',
    keterangan: 'Surat Jalan #SJ-SEP-001',
    tanggal: '2026-09-01',
    waktu: '09:30:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-09-01 09:30:00',
  },
  {
    id: 'trx-a-sep-02',
    store_id: 'store-a',
    inventory_id: 'inv-a-3',
    kode_barang: 'BAT-IP11-HC',
    nama_barang: 'Baterai iPhone 11 High Capacity 3500mAh',
    model_iphone: 'iPhone 11',
    harga_beli: 150000,
    harga_jual: 250000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 4,
    stok_sebelum: 12,
    stok_sesudah: 8,
    alasan: 'Ganti baterai customer service',
    keterangan: 'Nota Servis #MDN-1002',
    tanggal: '2026-09-02',
    waktu: '11:15:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-09-02 11:15:00',
  },
  {
    id: 'trx-a-sep-03',
    store_id: 'store-a',
    inventory_id: 'inv-a-5',
    kode_barang: 'CAM-IP12-MAIN',
    nama_barang: 'Kamera Belakang iPhone 12 Dual Cam Original',
    model_iphone: 'iPhone 12',
    harga_beli: 350000,
    harga_jual: 500000,
    jenis: 'RUSAK',
    direction: '-',
    jumlah: 1,
    stok_sebelum: 4,
    stok_sesudah: 3,
    alasan: 'Lensa retak saat pengiriman teknisi',
    keterangan: 'Klaim asuransi ekspedisi',
    tanggal: '2026-09-03',
    waktu: '14:20:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-09-03 14:20:00',
  },
  {
    id: 'trx-a-sep-04',
    store_id: 'store-a',
    inventory_id: 'inv-a-2',
    kode_barang: 'LCD-IP14PM-ORI',
    nama_barang: 'LCD iPhone 14 Pro Max OLED 120Hz ProMotion',
    model_iphone: 'iPhone 14 Pro Max',
    harga_beli: 1850000,
    harga_jual: 2400000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 8,
    stok_sebelum: 4,
    stok_sesudah: 12,
    alasan: 'Pengiriman sparepart premium',
    keterangan: 'Faktur #FK-0941',
    tanggal: '2026-09-04',
    waktu: '10:00:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-09-04 10:00:00',
  },
  {
    id: 'trx-a-sep-05',
    store_id: 'store-a',
    inventory_id: 'inv-a-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 3,
    stok_sebelum: 24,
    stok_sesudah: 21,
    alasan: 'Pemasangan LCD express',
    keterangan: 'Nota #MDN-1044',
    tanggal: '2026-09-05',
    waktu: '15:45:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-09-05 15:45:00',
  },
  {
    id: 'trx-a-sep-06-1',
    store_id: 'store-a',
    inventory_id: 'inv-a-10',
    kode_barang: 'SENSOR-IP12',
    nama_barang: 'Sensor Face ID & Earpiece Flex iPhone 12',
    model_iphone: 'iPhone 12',
    harga_beli: 250000,
    harga_jual: 350000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 6,
    stok_sebelum: 8,
    stok_sesudah: 14,
    alasan: 'Penerimaan pagi hari',
    keterangan: 'PO #9912',
    tanggal: '2026-09-06',
    waktu: '09:15:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-09-06 09:15:00',
  },
  {
    id: 'trx-a-sep-06-2',
    store_id: 'store-a',
    inventory_id: 'inv-a-3',
    kode_barang: 'BAT-IP11-HC',
    nama_barang: 'Baterai iPhone 11 High Capacity 3500mAh',
    model_iphone: 'iPhone 11',
    harga_beli: 150000,
    harga_jual: 250000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 2,
    stok_sebelum: 8,
    stok_sesudah: 6,
    alasan: 'Ganti baterai siang ini',
    keterangan: 'Pelanggan walk-in #MDN-1055',
    tanggal: '2026-09-06',
    waktu: '13:40:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-09-06 13:40:00',
  },
  {
    id: 'trx-a-sep-06-3',
    store_id: 'store-a',
    inventory_id: 'inv-a-9',
    kode_barang: 'TOOL-LEM-T7000',
    nama_barang: 'Lem LCD T-7000 Black 110ml Original Zhanlida',
    model_iphone: 'Universal / Multi-Model',
    harga_beli: 25000,
    harga_jual: 45000,
    jenis: 'RUSAK',
    direction: '-',
    jumlah: 1,
    stok_sebelum: 10,
    stok_sesudah: 9,
    alasan: 'Lem bocor saat penyimpanan',
    keterangan: 'Tutup pecah di rak',
    tanggal: '2026-09-06',
    waktu: '16:10:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-09-06 16:10:00',
  },
  // Store A - Historical Months 2026 (For Year Filter)
  {
    id: 'trx-a-hist-jan',
    store_id: 'store-a',
    inventory_id: 'inv-a-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 35,
    stok_sebelum: 0,
    stok_sesudah: 35,
    alasan: 'Stok Awal Tahun',
    keterangan: 'Initial Inventory',
    tanggal: '2026-01-15',
    waktu: '10:00:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-01-15 10:00:00',
  },
  {
    id: 'trx-a-hist-feb',
    store_id: 'store-a',
    inventory_id: 'inv-a-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 18,
    stok_sebelum: 35,
    stok_sesudah: 17,
    alasan: 'Penjualan Februari',
    keterangan: 'Rekap Februari',
    tanggal: '2026-02-20',
    waktu: '17:00:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-02-20 17:00:00',
  },
  {
    id: 'trx-a-hist-mar',
    store_id: 'store-a',
    inventory_id: 'inv-a-2',
    kode_barang: 'LCD-IP14PM-ORI',
    nama_barang: 'LCD iPhone 14 Pro Max OLED 120Hz ProMotion',
    model_iphone: 'iPhone 14 Pro Max',
    harga_beli: 1850000,
    harga_jual: 2400000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 22,
    stok_sebelum: 2,
    stok_sesudah: 24,
    alasan: 'Restock Maret',
    keterangan: 'Pengadaan Q1',
    tanggal: '2026-03-18',
    waktu: '11:30:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-03-18 11:30:00',
  },
  {
    id: 'trx-a-hist-apr',
    store_id: 'store-a',
    inventory_id: 'inv-a-3',
    kode_barang: 'BAT-IP11-HC',
    nama_barang: 'Baterai iPhone 11 High Capacity 3500mAh',
    model_iphone: 'iPhone 11',
    harga_beli: 150000,
    harga_jual: 250000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 25,
    stok_sebelum: 30,
    stok_sesudah: 5,
    alasan: 'Penjualan April Ramadan',
    keterangan: 'Promo Lebaran Service',
    tanggal: '2026-04-12',
    waktu: '16:00:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-04-12 16:00:00',
  },
  {
    id: 'trx-a-hist-may',
    store_id: 'store-a',
    inventory_id: 'inv-a-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 40,
    stok_sebelum: 5,
    stok_sesudah: 45,
    alasan: 'Restock Mei',
    keterangan: 'Pasokan Impor Baru',
    tanggal: '2026-05-10',
    waktu: '10:15:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-05-10 10:15:00',
  },
  {
    id: 'trx-a-hist-jun',
    store_id: 'store-a',
    inventory_id: 'inv-a-5',
    kode_barang: 'CAM-IP12-MAIN',
    nama_barang: 'Kamera Belakang iPhone 12 Dual Cam Original',
    model_iphone: 'iPhone 12',
    harga_beli: 350000,
    harga_jual: 500000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 14,
    stok_sebelum: 20,
    stok_sesudah: 6,
    alasan: 'Pemakaian service Juni',
    keterangan: 'Rekap Q2',
    tanggal: '2026-06-22',
    waktu: '15:20:00',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    created_at: '2026-06-22 15:20:00',
  },
  {
    id: 'trx-a-hist-jul',
    store_id: 'store-a',
    inventory_id: 'inv-a-2',
    kode_barang: 'LCD-IP14PM-ORI',
    nama_barang: 'LCD iPhone 14 Pro Max OLED 120Hz ProMotion',
    model_iphone: 'iPhone 14 Pro Max',
    harga_beli: 1850000,
    harga_jual: 2400000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 28,
    stok_sebelum: 6,
    stok_sesudah: 34,
    alasan: 'Restock Juli',
    keterangan: 'Faktur JKT-771',
    tanggal: '2026-07-16',
    waktu: '11:00:00',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    created_at: '2026-07-16 11:00:00',
  },
  // Store B, C, D, E transactions for comprehensive stats
  {
    id: 'trx-b-sep-01',
    store_id: 'store-b',
    inventory_id: 'inv-b-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 18,
    stok_sebelum: 2,
    stok_sesudah: 20,
    alasan: 'Restock Jakarta Roxy',
    keterangan: 'Batch Roxy 01',
    tanggal: '2026-09-02',
    waktu: '10:00:00',
    user_id: 'user-admin-b',
    user_name: 'Hendra Gunawan',
    created_at: '2026-09-02 10:00:00',
  },
  {
    id: 'trx-b-sep-02',
    store_id: 'store-b',
    inventory_id: 'inv-b-2',
    kode_barang: 'BAT-IP13PM-HC',
    nama_barang: 'Baterai iPhone 13 Pro Max 4352mAh High Capacity',
    model_iphone: 'iPhone 13 Pro Max',
    harga_beli: 190000,
    harga_jual: 295000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 5,
    stok_sebelum: 7,
    stok_sesudah: 2,
    alasan: 'Terjual service Jakarta',
    keterangan: 'Nota #JKT-8821',
    tanggal: '2026-09-05',
    waktu: '14:30:00',
    user_id: 'user-admin-b',
    user_name: 'Hendra Gunawan',
    created_at: '2026-09-05 14:30:00',
  },
  {
    id: 'trx-c-sep-01',
    store_id: 'store-c',
    inventory_id: 'inv-c-1',
    kode_barang: 'LCD-IP15-OLED',
    nama_barang: 'LCD iPhone 15 Dynamic Island Super Retina XDR',
    model_iphone: 'iPhone 15',
    harga_beli: 1200000,
    harga_jual: 1650000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 10,
    stok_sebelum: 1,
    stok_sesudah: 11,
    alasan: 'Restock Surabaya Marina',
    keterangan: 'Faktur SBY-001',
    tanggal: '2026-09-03',
    waktu: '11:00:00',
    user_id: 'user-admin-c',
    user_name: 'Rudi Hermawan',
    created_at: '2026-09-03 11:00:00',
  },
  {
    id: 'trx-c-sep-02',
    store_id: 'store-c',
    inventory_id: 'inv-c-1',
    kode_barang: 'LCD-IP15-OLED',
    nama_barang: 'LCD iPhone 15 Dynamic Island Super Retina XDR',
    model_iphone: 'iPhone 15',
    harga_beli: 1200000,
    harga_jual: 1650000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 3,
    stok_sebelum: 11,
    stok_sesudah: 8,
    alasan: 'Ganti LCD Surabaya',
    keterangan: 'Nota SBY-812',
    tanggal: '2026-09-06',
    waktu: '15:10:00',
    user_id: 'user-admin-c',
    user_name: 'Rudi Hermawan',
    created_at: '2026-09-06 15:10:00',
  },
  {
    id: 'trx-d-sep-01',
    store_id: 'store-d',
    inventory_id: 'inv-d-1',
    kode_barang: 'LCD-IP12P-OLED',
    nama_barang: 'LCD iPhone 12 Pro OLED RJ Premium',
    model_iphone: 'iPhone 12 Pro',
    harga_beli: 520000,
    harga_jual: 720000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 12,
    stok_sebelum: 2,
    stok_sesudah: 14,
    alasan: 'Restock Bandung BEC',
    keterangan: 'Surat Jalan BDG-10',
    tanggal: '2026-09-01',
    waktu: '10:45:00',
    user_id: 'user-admin-d',
    user_name: 'Asep Kusnadi',
    created_at: '2026-09-01 10:45:00',
  },
  {
    id: 'trx-e-sep-01',
    store_id: 'store-e',
    inventory_id: 'inv-e-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'MASUK',
    direction: '+',
    jumlah: 15,
    stok_sebelum: 1,
    stok_sesudah: 16,
    alasan: 'Restock Makassar Karebosi',
    keterangan: 'Ekspedisi Laut MKS-09',
    tanggal: '2026-09-02',
    waktu: '11:30:00',
    user_id: 'user-admin-e',
    user_name: 'Faisal Ramli',
    created_at: '2026-09-02 11:30:00',
  },
  {
    id: 'trx-e-sep-02',
    store_id: 'store-e',
    inventory_id: 'inv-e-1',
    kode_barang: 'LCD-IP13-OLED',
    nama_barang: 'LCD iPhone 13 OLED GX Original Quality',
    model_iphone: 'iPhone 13',
    harga_beli: 450000,
    harga_jual: 650000,
    jenis: 'KELUAR',
    direction: '-',
    jumlah: 5,
    stok_sebelum: 16,
    stok_sesudah: 11,
    alasan: 'Service ganti LCD Makassar',
    keterangan: 'Nota MKS-441',
    tanggal: '2026-09-06',
    waktu: '14:20:00',
    user_id: 'user-admin-e',
    user_name: 'Faisal Ramli',
    created_at: '2026-09-06 14:20:00',
  },
];

export const INITIAL_RETURNS: ReturnItem[] = [
  {
    id: 'ret-001',
    store_id: 'store-a',
    inventory_id: 'inv-a-2',
    kode_barang: 'LCD-IP14PM-ORI',
    nama_barang: 'LCD iPhone 14 Pro Max OLED 120Hz ProMotion',
    model_iphone: 'iPhone 14 Pro Max',
    harga_beli: 1850000,
    harga_jual: 2400000,
    jumlah: 1,
    tanggal_return: '2026-08-31',
    tanggal_pengajuan: '2026-08-31',
    customer_name: 'Budi Pratama',
    customer_phone: '081299887766',
    alasan: 'Flex LCD ada crack mikroskopis dari batch baru',
    alasan_return: 'Flex LCD ada crack mikroskopis dari batch baru',
    keterangan: 'Customer komplain touch kadang ghosting setelah 1 hari pasang',
    status: 'MENUNGGU',
    dibuat_oleh_id: 'user-staff-a1',
    dibuat_oleh_name: 'Dimas Prasetyo',
    created_at: '2026-08-31 15:10:00',
  },
  {
    id: 'ret-002',
    store_id: 'store-a',
    inventory_id: 'inv-a-3',
    kode_barang: 'BAT-IP11-HC',
    nama_barang: 'Baterai iPhone 11 High Capacity 3500mAh',
    model_iphone: 'iPhone 11',
    harga_beli: 150000,
    harga_jual: 250000,
    jumlah: 2,
    tanggal_return: '2026-08-25',
    tanggal_pengajuan: '2026-08-25',
    customer_name: 'Siti Rahma',
    customer_phone: '085712345678',
    alasan: 'Kembung saat unboxing awal',
    alasan_return: 'Kembung saat unboxing awal',
    keterangan: 'Segel utuh, diganti unit baru oleh supplier',
    status: 'DITERIMA',
    dibuat_oleh_id: 'user-staff-a1',
    dibuat_oleh_name: 'Dimas Prasetyo',
    diproses_oleh_id: 'user-admin-a',
    diproses_oleh_name: 'Budi Santoso',
    tanggal_proses: '2026-08-26 09:00:00',
    catatan_proses: 'Barang pengganti sudah masuk stok kembali',
    catatan_approval: 'Barang pengganti sudah masuk stok kembali',
    created_at: '2026-08-25 11:00:00',
  },
  {
    id: 'ret-003',
    store_id: 'store-a',
    inventory_id: 'inv-a-8',
    kode_barang: 'BG-IP13-BLUE',
    nama_barang: 'Backglass Kaca Belakang iPhone 13 Big Hole Blue',
    model_iphone: 'iPhone 13',
    harga_beli: 60000,
    harga_jual: 120000,
    jumlah: 1,
    tanggal_return: '2026-08-20',
    tanggal_pengajuan: '2026-08-20',
    customer_name: 'Doni Firmansyah',
    customer_phone: '087812349999',
    alasan: 'Salah tipe pemesanan oleh teknisi (pesan Mini bukan reguler)',
    alasan_return: 'Salah tipe pemesanan oleh teknisi (pesan Mini bukan reguler)',
    keterangan: 'Kemasan sudah sobek dan terkena lem',
    status: 'DITOLAK',
    dibuat_oleh_id: 'user-staff-a2',
    dibuat_oleh_name: 'Rian Pratama',
    diproses_oleh_id: 'user-admin-a',
    diproses_oleh_name: 'Budi Santoso',
    tanggal_proses: '2026-08-21 14:00:00',
    catatan_proses: 'Ditolak karena segel fisik rusak dan human error toko sendiri',
    catatan_approval: 'Ditolak karena segel fisik rusak dan human error toko sendiri',
    created_at: '2026-08-20 16:20:00',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  // Dimas Prasetyo (Karyawan Toko A) Attendance History
  {
    id: 'att-dimas-01',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-09-01',
    jam_masuk: '08:35 WIB',
    jam_keluar: '17:05 WIB',
    jam_pulang: '17:05 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-09-01 08:35:00',
  },
  {
    id: 'att-dimas-02',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-08-31',
    jam_masuk: '08:30 WIB',
    jam_keluar: '17:05 WIB',
    jam_pulang: '17:05 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-08-31 08:30:00',
  },
  {
    id: 'att-dimas-03',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-08-30',
    jam_masuk: '08:25 WIB',
    jam_keluar: '17:15 WIB',
    jam_pulang: '17:15 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-08-30 08:25:00',
  },
  {
    id: 'att-dimas-04',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-08-29',
    jam_masuk: '09:10 WIB',
    jam_keluar: '17:30 WIB',
    jam_pulang: '17:30 WIB',
    status: 'TERLAMBAT',
    keterangan: 'Hujan deras dan macet di jalan',
    catatan: 'Hujan deras dan macet di jalan',
    created_at: '2026-08-29 09:10:00',
  },
  {
    id: 'att-dimas-05',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-08-28',
    jam_masuk: '08:20 WIB',
    jam_keluar: '17:00 WIB',
    jam_pulang: '17:00 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-08-28 08:20:00',
  },
  {
    id: 'att-dimas-06',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-08-27',
    jam_masuk: null,
    jam_keluar: null,
    jam_pulang: null,
    status: 'IZIN',
    keterangan: 'Izin mengurus perpanjangan SIM kendaraan',
    catatan: 'Izin mengurus perpanjangan SIM kendaraan',
    created_at: '2026-08-27 07:30:00',
  },
  {
    id: 'att-dimas-07',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-08-26',
    jam_masuk: '08:35 WIB',
    jam_keluar: '17:00 WIB',
    jam_pulang: '17:00 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-08-26 08:35:00',
  },

  // Budi Santoso (Admin Toko A)
  {
    id: 'att-001',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-09-01',
    jam_masuk: '08:25 WIB',
    jam_keluar: '17:30 WIB',
    jam_pulang: '17:30 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-09-01 08:25:00',
  },
  {
    id: 'att-budi-02',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-08-31',
    jam_masuk: '08:15 WIB',
    jam_keluar: '17:30 WIB',
    jam_pulang: '17:30 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-08-31 08:15:00',
  },

  // Rian Pratama (Karyawan Toko A)
  {
    id: 'att-003',
    user_id: 'user-staff-a2',
    user_name: 'Rian Pratama',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    tanggal: '2026-09-01',
    jam_masuk: null,
    jam_keluar: null,
    jam_pulang: null,
    status: 'IZIN',
    keterangan: 'Izin urusan keluarga (surat terlampir)',
    catatan: 'Izin urusan keluarga (surat terlampir)',
    created_at: '2026-09-01 07:30:00',
  },

  // Hendra Gunawan (Admin Toko B)
  {
    id: 'att-004',
    user_id: 'user-admin-b',
    user_name: 'Hendra Gunawan',
    store_id: 'store-b',
    store_name: 'Toko B (Jakarta Barat)',
    tanggal: '2026-09-01',
    jam_masuk: '08:50 WIB',
    jam_keluar: '18:00 WIB',
    jam_pulang: '18:00 WIB',
    status: 'HADIR',
    keterangan: 'Hadir',
    catatan: 'Hadir',
    created_at: '2026-09-01 08:50:00',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    user_id: 'user-super',
    user_name: 'Alfin Maulana',
    role: 'SUPER_ADMIN',
    store_id: null,
    store_name: 'Semua Toko (Pusat)',
    aktivitas: 'Konfigurasi Jam Kerja Global',
    detail_perubahan: 'Memperbarui standar jam masuk & pulang seluruh 5 cabang toko',
    waktu: '2026-09-02 07:45:00',
    tipe: 'STORE',
  },
  {
    id: 'log-002',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    role: 'ADMIN_TOKO',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    aktivitas: 'Check In Absensi',
    detail_perubahan: 'Status HADIR tepat waktu pukul 08:25 WIB',
    waktu: '2026-09-02 08:25:00',
    tipe: 'ABSENSI',
  },
  {
    id: 'log-003',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    role: 'KARYAWAN',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    aktivitas: 'Check In Absensi',
    detail_perubahan: 'Status HADIR pukul 08:28 WIB (Shift Pagi)',
    waktu: '2026-09-02 08:28:00',
    tipe: 'ABSENSI',
  },
  {
    id: 'log-004',
    user_id: 'user-staff-a2',
    user_name: 'Rian Hidayat',
    role: 'KARYAWAN',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    aktivitas: 'Check In Absensi (TERLAMBAT)',
    detail_perubahan: 'Status TERLAMBAT pukul 08:45 WIB (Standar: 08:30 WIB)',
    waktu: '2026-09-02 08:45:00',
    tipe: 'ABSENSI',
  },
  {
    id: 'log-005',
    user_id: 'user-admin-a',
    user_name: 'Budi Santoso',
    role: 'ADMIN_TOKO',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    aktivitas: 'Tambah Stok Barang',
    detail_perubahan: 'LCD-IP13-OLED: +20 pcs (Stok: 4 → 24) [Alasan: Restock pengiriman Gudang]',
    waktu: '2026-09-01 10:15:00',
    tipe: 'INVENTORY',
  },
  {
    id: 'log-006',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    role: 'KARYAWAN',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    aktivitas: 'Barang Keluar (Pemasangan)',
    detail_perubahan: 'LCD-IP13-OLED: -1 pcs (Stok: 24 → 23) [Servis iPhone 13 Reguler]',
    waktu: '2026-09-01 14:30:00',
    tipe: 'INVENTORY',
  },
  {
    id: 'log-007',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    role: 'KARYAWAN',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    aktivitas: 'Buat Pengajuan Return',
    detail_perubahan: 'LCD-IP14PM-ORI (1 pcs): Status MENUNGGU verifikasi admin toko',
    waktu: '2026-09-01 15:10:00',
    tipe: 'RETURN',
  },
  {
    id: 'log-008',
    user_id: 'user-admin-b',
    user_name: 'Hendra Gunawan',
    role: 'ADMIN_TOKO',
    store_id: 'store-b',
    store_name: 'Toko B (Jakarta Barat)',
    aktivitas: 'Check In Absensi',
    detail_perubahan: 'Status HADIR tepat waktu pukul 08:50 WIB',
    waktu: '2026-09-02 08:50:00',
    tipe: 'ABSENSI',
  },
  {
    id: 'log-009',
    user_id: 'user-staff-b1',
    user_name: 'Bambang Tri',
    role: 'KARYAWAN',
    store_id: 'store-b',
    store_name: 'Toko B (Jakarta Barat)',
    aktivitas: 'Check In Absensi',
    detail_perubahan: 'Status HADIR pukul 08:55 WIB',
    waktu: '2026-09-02 08:55:00',
    tipe: 'ABSENSI',
  },
  {
    id: 'log-010',
    user_id: 'user-admin-b',
    user_name: 'Hendra Gunawan',
    role: 'ADMIN_TOKO',
    store_id: 'store-b',
    store_name: 'Toko B (Jakarta Barat)',
    aktivitas: 'Tambah Seri iPhone',
    detail_perubahan: 'Mendaftarkan seri baru iPhone 16 Pro Max',
    waktu: '2026-09-01 11:20:00',
    tipe: 'INVENTORY',
  },
  {
    id: 'log-011',
    user_id: 'user-admin-c',
    user_name: 'Rudi Hermawan',
    role: 'ADMIN_TOKO',
    store_id: 'store-c',
    store_name: 'Toko C (Surabaya)',
    aktivitas: 'Check In Absensi',
    detail_perubahan: 'Status HADIR pukul 09:45 WIB',
    waktu: '2026-09-02 09:45:00',
    tipe: 'ABSENSI',
  },
  {
    id: 'log-012',
    user_id: 'user-staff-c1',
    user_name: 'Doni Pratama',
    role: 'KARYAWAN',
    store_id: 'store-c',
    store_name: 'Toko C (Surabaya)',
    aktivitas: 'Pengurangan Stok',
    detail_perubahan: 'BAT-IP13P-ORI: -2 pcs untuk penggantian baterai customer',
    waktu: '2026-09-01 16:15:00',
    tipe: 'INVENTORY',
  },
  {
    id: 'log-013',
    user_id: 'user-staff-a1',
    user_name: 'Dimas Prasetyo',
    role: 'KARYAWAN',
    store_id: 'store-a',
    store_name: 'Toko A (Medan)',
    aktivitas: 'Lapor Barang Rusak',
    detail_perubahan: 'Komponen Rusak/Defect: LCD-IP13-OLED - LCD iPhone 13 (iPhone 13) sebanyak 1 pcs. Alasan: Garis layar saat pengetesan teknisi (Dead on Arrival). (Stok: 24 → 23 pcs)',
    waktu: '2026-09-01 11:45:00',
    tipe: 'INVENTORY',
  },
  {
    id: 'log-014',
    user_id: 'user-staff-b1',
    user_name: 'Bambang Tri',
    role: 'KARYAWAN',
    store_id: 'store-b',
    store_name: 'Toko B (Jakarta Barat)',
    aktivitas: 'Lapor Barang Rusak',
    detail_perubahan: 'Komponen Rusak/Defect: CAM-IP13P-ORI - Kamera Belakang iPhone 13 Pro (iPhone 13 Pro) sebanyak 1 pcs. Alasan: Sensor fokus getar / cacat supplier. (Stok: 8 → 7 pcs)',
    waktu: '2026-09-01 13:20:00',
    tipe: 'INVENTORY',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  // --- NOTIFIKASI GLOBAL LINTAS CABANG (Khusus Super Admin di Dashboard Utama) ---
  {
    id: 'notif-global-1',
    store_id: null,
    is_global: true,
    target_roles: ['SUPER_ADMIN'],
    kategori: 'INVENTORY',
    tipe: 'DANGER',
    judul: 'Peringatan: Stok Kritis Lintas Cabang',
    pesan: '2 komponen sparepart kehabisan stok dan 4 komponen menipis. Segera lakukan koordinasi pengadaan pusat.',
    waktu: '1 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'INVENTARIS',
  },
  {
    id: 'notif-global-2',
    store_id: null,
    is_global: true,
    target_roles: ['SUPER_ADMIN'],
    kategori: 'RETURN',
    tipe: 'INFO',
    judul: 'Monitoring: Total Pengajuan Return Aktif',
    pesan: 'Terdapat pengajuan return aktif yang memerlukan pemantauan manajemen.',
    waktu: '2 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'RETURN',
  },

  // --- NOTIFIKASI TOKO A ---
  {
    id: 'notif-a1',
    store_id: 'store-a',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO'],
    creator_id: 'user-staff-a1',
    creator_name: 'Dimas Prasetyo',
    kategori: 'RETURN',
    tipe: 'INFO',
    judul: 'Pengajuan Return Menunggu Approval',
    pesan: 'Dimas Prasetyo mengajukan 1 pcs return untuk LCD-IP14PM-ORI. Membutuhkan verifikasi Kepala Toko.',
    waktu: '30 menit yang lalu',
    read: false,
    read_by: [],
    link_page: 'RETURN',
  },
  {
    id: 'notif-a2',
    store_id: 'store-a',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO'],
    creator_id: 'user-staff-a1',
    creator_name: 'Dimas Prasetyo',
    kategori: 'INVENTORY',
    tipe: 'WARNING',
    judul: 'Laporan Barang Rusak: LCD iPhone 13',
    pesan: 'Dimas Prasetyo melaporkan 1 pcs LCD iPhone 13 rusak saat pengetesan teknisi. Sisa stok: 23 pcs.',
    waktu: '1 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'BARANG_RUSAK',
  },
  {
    id: 'notif-a3',
    store_id: 'store-a',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO', 'KARYAWAN'],
    kategori: 'INVENTORY',
    tipe: 'DANGER',
    judul: 'Stok Habis: Baterai iPhone 12 Original',
    pesan: 'Stok BAT-IP12-ORI tersisa 0 pcs. Harap diperhatikan teknisi saat menerima servis customer.',
    waktu: '2 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'INVENTARIS',
  },
  {
    id: 'notif-a4',
    store_id: 'store-a',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO', 'KARYAWAN'],
    kategori: 'INVENTORY',
    tipe: 'WARNING',
    judul: 'Stok Menipis: LCD iPhone 14 Pro Max',
    pesan: 'Sisa stok LCD-IP14PM-ORI hanya 4 pcs (Batas minimum: 5 pcs).',
    waktu: '3 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'INVENTARIS',
  },
  {
    id: 'notif-a5',
    store_id: 'store-a',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO'],
    kategori: 'ABSENSI',
    tipe: 'WARNING',
    judul: 'Keterlambatan Absensi: Rian Pratama',
    pesan: 'Rian Pratama check in pada 08:45 WIB (Terlambat 15 menit dari jadwal 08:30 WIB).',
    waktu: '4 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'ABSENSI',
  },
  {
    id: 'notif-a6',
    store_id: 'store-a',
    target_roles: ['KARYAWAN'],
    target_user_id: 'user-staff-a1',
    creator_id: 'user-admin-a',
    creator_name: 'Budi Santoso',
    kategori: 'RETURN',
    tipe: 'SUCCESS',
    judul: 'Pengajuan Return Anda Diterima',
    pesan: 'Pengajuan return 1 pcs Kamera iPhone 12 Anda telah disetujui oleh Budi Santoso.',
    waktu: '5 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'RETURN',
  },
  {
    id: 'notif-a7',
    store_id: 'store-a',
    target_roles: ['KARYAWAN'],
    target_user_id: 'user-staff-a1',
    kategori: 'ABSENSI',
    tipe: 'SUCCESS',
    judul: 'Absensi Masuk Berhasil',
    pesan: 'Check in kehadiran Anda hari ini tercatat pukul 08:22 WIB (Tepat Waktu). Selamat bekerja!',
    waktu: '6 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'ABSENSI',
  },

  // --- NOTIFIKASI TOKO B ---
  {
    id: 'notif-b1',
    store_id: 'store-b',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO'],
    creator_id: 'user-staff-b1',
    creator_name: 'Kevin Wijaya',
    kategori: 'INVENTORY',
    tipe: 'WARNING',
    judul: 'Laporan Barang Rusak: Kamera iPhone 13 Pro',
    pesan: 'Kevin Wijaya melaporkan 1 pcs Kamera Belakang iPhone 13 Pro defect sensor getar. Sisa stok: 7 pcs.',
    waktu: '1 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'BARANG_RUSAK',
  },
  {
    id: 'notif-b2',
    store_id: 'store-b',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO', 'KARYAWAN'],
    kategori: 'INVENTORY',
    tipe: 'DANGER',
    judul: 'Stok Habis: LCD iPhone 11 Original',
    pesan: 'Stok LCD-IP11-ORI tersisa 0 pcs. Segera lakukan PO pengadaan.',
    waktu: '2 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'INVENTARIS',
  },
  {
    id: 'notif-b3',
    store_id: 'store-b',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO', 'KARYAWAN'],
    kategori: 'INVENTORY',
    tipe: 'WARNING',
    judul: 'Stok Menipis: Baterai iPhone 13 Pro',
    pesan: 'Sisa stok BAT-IP13P-ORI hanya 2 pcs (Batas minimum: 5 pcs).',
    waktu: '3 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'INVENTARIS',
  },
  {
    id: 'notif-b4',
    store_id: 'store-b',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO'],
    creator_id: 'user-staff-b1',
    creator_name: 'Kevin Wijaya',
    kategori: 'RETURN',
    tipe: 'INFO',
    judul: 'Pengajuan Return Menunggu Approval',
    pesan: 'Kevin Wijaya mengajukan 1 pcs return untuk Fleksibel Port iPhone 11.',
    waktu: '4 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'RETURN',
  },
  {
    id: 'notif-b5',
    store_id: 'store-b',
    target_roles: ['KARYAWAN'],
    target_user_id: 'user-staff-b1',
    kategori: 'RETURN',
    tipe: 'INFO',
    judul: 'Status Pengajuan Return Anda',
    pesan: 'Pengajuan return Fleksibel Port iPhone 11 Anda sedang menunggu verifikasi dari Hendra Gunawan.',
    waktu: '4 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'RETURN',
  },
  {
    id: 'notif-b6',
    store_id: 'store-b',
    target_roles: ['KARYAWAN'],
    target_user_id: 'user-staff-b1',
    kategori: 'ABSENSI',
    tipe: 'SUCCESS',
    judul: 'Absensi Masuk Berhasil',
    pesan: 'Check in kehadiran Anda tercatat pukul 08:55 WIB (Tepat Waktu).',
    waktu: '5 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'ABSENSI',
  },

  // --- NOTIFIKASI TOKO C ---
  {
    id: 'notif-c1',
    store_id: 'store-c',
    target_roles: ['SUPER_ADMIN', 'ADMIN_TOKO', 'KARYAWAN'],
    kategori: 'INVENTORY',
    tipe: 'WARNING',
    judul: 'Stok Menipis: Kamera Depan iPhone 12',
    pesan: 'Sisa stok CAM-IP12-FRT tersisa 3 pcs (Batas minimum: 5 pcs).',
    waktu: '2 jam yang lalu',
    read: false,
    read_by: [],
    link_page: 'INVENTARIS',
  },
];
